// <auto-generated />
namespace EnFu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removeBibleReadingColumnNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeBibleReadingColumnNames));
        
        string IMigrationMetadata.Id
        {
            get { return "202201051612424_removeBibleReadingColumnNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
